server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/administrationService
    username: admin
    password: ilia
  flyway:
    jdbc-properties:
      enabled: true
      locations:
        - db.migration

springdoc:
  swagger-ui:
    enabled: true
