server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/hostelService

otlp:
  tracing:
    export-enabled: false
    endpoint: http://localhost:4317

rest:
  base-url:
    notification-service: http://localhost:8085