openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8083
  description: Generated server url
paths:
  /documents:
    post:
      tags:
      - document-controller
      operationId: addDocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponseDto"
  /balance:
    post:
      tags:
      - balance-controller
      operationId: addBalance
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponseDto"
  /documents/edit:
    patch:
      tags:
      - document-controller
      operationId: editDocument
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentEditRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponseDto"
  /balance/edit:
    patch:
      tags:
      - balance-controller
      operationId: editBalance
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponseDto"
  /balance/edit/adding:
    patch:
      tags:
      - balance-controller
      operationId: editAddBalance
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BalanceRequestDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponseDto"
  /documents/get/type/{documentType}/user/{userId}:
    get:
      tags:
      - document-controller
      operationId: getDocumentByType
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: documentType
        in: path
        required: true
        schema:
          type: string
          enum:
          - CERTIFICATE
          - FLUOROGRAPHY
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponseDto"
  /documents/get/by/id/{id}:
    get:
      tags:
      - document-controller
      operationId: getDocumentById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DocumentResponseDto"
  /documents/get/all:
    get:
      tags:
      - document-controller
      operationId: getAllDocuments
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1000000000
      - name: fluraPast
        in: query
        required: false
        schema:
          type: boolean
      - name: fluraDate
        in: query
        required: false
        schema:
          type: string
          format: date
      - name: certPast
        in: query
        required: false
        schema:
          type: boolean
      - name: certDate
        in: query
        required: false
        schema:
          type: string
          format: date
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DocumentResponseDto"
  /documents/get/all/user/{userId}:
    get:
      tags:
      - document-controller
      operationId: getAllDocumentsByUser
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DocumentResponseDto"
  /documents/get/all/by/users:
    get:
      tags:
      - document-controller
      operationId: getAllDocumentsByUsers
      parameters:
      - name: userIds
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DocumentResponseDto"
  /balance/get/{id}:
    get:
      tags:
      - balance-controller
      operationId: getBalance
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponseDto"
  /balance/get/short/{id}:
    get:
      tags:
      - balance-controller
      operationId: getBalanceShort
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceShortResponseDto"
  /balance/get/all:
    get:
      tags:
      - balance-controller
      operationId: getAllBalances
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1000000000
      - name: negative
        in: query
        required: false
        schema:
          type: boolean
      - name: value
        in: query
        required: false
        schema:
          type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BalanceResponseDto"
  /balance/get/all/by/users:
    get:
      tags:
      - balance-controller
      operationId: getAllBalancesByUsers
      parameters:
      - name: userIds
        in: query
        required: true
        schema:
          type: array
          items:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BalanceResponseDto"
components:
  schemas:
    DocumentRequestDto:
      type: object
      properties:
        user:
          type: string
          format: uuid
        type:
          type: string
          enum:
          - CERTIFICATE
          - FLUOROGRAPHY
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
      required:
      - endDate
      - startDate
      - type
      - user
    DocumentResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user:
          type: string
          format: uuid
        type:
          type: string
          enum:
          - CERTIFICATE
          - FLUOROGRAPHY
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
    BalanceRequestDto:
      type: object
      properties:
        user:
          type: string
          format: uuid
        balance:
          type: number
      required:
      - balance
      - user
    BalanceResponseDto:
      type: object
      properties:
        user:
          type: string
          format: uuid
        balance:
          type: number
    DocumentEditRequestDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
      required:
      - endDate
      - id
      - startDate
    BalanceShortResponseDto:
      type: object
      properties:
        balance:
          type: number
